/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedOverviewRouteImport } from './routes/_protected/overview'
import { Route as ProtectedLibraryRouteImport } from './routes/_protected/library'
import { Route as ProtectedEditorLostRouteImport } from './routes/_protected/editor-lost'
import { Route as ProtectedEditorRouteImport } from './routes/_protected/editor'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOverviewRoute = ProtectedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedLibraryRoute = ProtectedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedEditorLostRoute = ProtectedEditorLostRouteImport.update({
  id: '/editor-lost',
  path: '/editor-lost',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedEditorRoute = ProtectedEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/editor': typeof ProtectedEditorRoute
  '/editor-lost': typeof ProtectedEditorLostRoute
  '/library': typeof ProtectedLibraryRoute
  '/overview': typeof ProtectedOverviewRoute
  '/settings': typeof ProtectedSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/editor': typeof ProtectedEditorRoute
  '/editor-lost': typeof ProtectedEditorLostRoute
  '/library': typeof ProtectedLibraryRoute
  '/overview': typeof ProtectedOverviewRoute
  '/settings': typeof ProtectedSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/editor': typeof ProtectedEditorRoute
  '/_protected/editor-lost': typeof ProtectedEditorLostRoute
  '/_protected/library': typeof ProtectedLibraryRoute
  '/_protected/overview': typeof ProtectedOverviewRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/editor'
    | '/editor-lost'
    | '/library'
    | '/overview'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/editor'
    | '/editor-lost'
    | '/library'
    | '/overview'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/editor'
    | '/_protected/editor-lost'
    | '/_protected/library'
    | '/_protected/overview'
    | '/_protected/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/overview': {
      id: '/_protected/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof ProtectedOverviewRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/library': {
      id: '/_protected/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ProtectedLibraryRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/editor-lost': {
      id: '/_protected/editor-lost'
      path: '/editor-lost'
      fullPath: '/editor-lost'
      preLoaderRoute: typeof ProtectedEditorLostRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/editor': {
      id: '/_protected/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof ProtectedEditorRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedEditorRoute: typeof ProtectedEditorRoute
  ProtectedEditorLostRoute: typeof ProtectedEditorLostRoute
  ProtectedLibraryRoute: typeof ProtectedLibraryRoute
  ProtectedOverviewRoute: typeof ProtectedOverviewRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedEditorRoute: ProtectedEditorRoute,
  ProtectedEditorLostRoute: ProtectedEditorLostRoute,
  ProtectedLibraryRoute: ProtectedLibraryRoute,
  ProtectedOverviewRoute: ProtectedOverviewRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
